
name: minio

services:
  minio:
    image: minio/minio:latest
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: Pa22word22
    command: ["server", "--console-address", ":9001", "/data"]


  minio-setup:
    image: minio/mc:latest
    depends_on:
      - minio
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: Pa22word22
    entrypoint: >
      /bin/sh -c "
      echo 'Waiting for Minio to start...' &&
      /bin/sleep 10 &&
      mc alias set minio http://minio:9000 $$MINIO_ACCESS_KEY $$MINIO_SECRET_KEY &&
      mc mb minio/my-content-engine &&
      echo 'Minio setup complete'"


volumes:
 
  minio-data: