name: devcontainer-test


services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/joshyorko/joshyorko_devcontainer:latest
    volumes:
      - ../..:/workspaces:cached
    networks:
      - devcontainer-network
    command: sleep infinity

 

networks:
  devcontainer-network:

